services:
  app:
    build: .
    ports:
      - "7290:7290"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - quote_data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7290/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 768M
    restart: unless-stopped

volumes:
  quote_data:
    driver: local